fixup! drm/xe/display: Implement display support
When selecting CONFIG_XE_DISPLAY, the following missing symbols can be
seen unless something else has selected the corresponding configs.

ERROR: modpost: "cfb_copyarea" [drivers/gpu/drm/xe/xe.ko] undefined!
ERROR: modpost: "cfb_fillrect" [drivers/gpu/drm/xe/xe.ko] undefined!
ERROR: modpost: "cfb_imageblit" [drivers/gpu/drm/xe/xe.ko] undefined

Make sure these are included in the Xe Display build.

v2:
- Use "select FB_IOMEM_HELPERS" (Maarten Lankhorst)

Cc: Maarten Lankhorst <maarten.lankhorst@linux.intel.com>
Signed-off-by: Thomas Hellström <thomas.hellstrom@linux.intel.com>
Reviewed-by: Maarten Lankhorst <maarten.lankhorst@linux.intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20230919083627.10955-1-thomas.hellstrom@linux.intel.com