drm/xe/uapi: Fix indentation issues that sometimes causes build warning
These issues were not seeing every time, but once another error was hit
these were printed out:

./include/uapi/drm/xe_drm.h:493: WARNING: Definition list ends without \
 a blank line; unexpected unindent.
./include/uapi/drm/xe_drm.h:500: ERROR: Unexpected indentation.
./include/uapi/drm/xe_drm.h:501: WARNING: Block quote ends without a \
 blank line; unexpected unindent.

This patch fixes the build issues, but also the presentation of the
uc_type list in the build html doc.

Signed-off-by: Rodrigo Vivi <rodrigo.vivi@intel.com>