fixup! drm/xe/display: Implement display support
Add missing header to fix warning while building with W=1:

	  CC [M]  drivers/gpu/drm/xe/display/intel_fbdev_fb.o
	../drivers/gpu/drm/xe/display/intel_fbdev_fb.c:14:25: error: no previous prototype for ‘intel_fbdev_fb_alloc’ [-Werror=missing-prototypes]
	   14 | struct drm_framebuffer *intel_fbdev_fb_alloc(struct drm_fb_helper *helper,
	      |                         ^~~~~~~~~~~~~~~~~~~~
	../drivers/gpu/drm/xe/display/intel_fbdev_fb.c:77:5: error: no previous prototype for ‘intel_fbdev_fb_fill_info’ [-Werror=missing-prototypes]
	   77 | int intel_fbdev_fb_fill_info(struct drm_i915_private *i915, struct fb_info *info,
	      |     ^~~~~~~~~~~~~~~~~~~~~~~~
	cc1: all warnings being treated as errors

Reviewed-by: Gustavo Sousa <gustavo.sousa@intel.com>
Link: https://lore.kernel.org/r/20231117175624.535520-2-lucas.demarchi@intel.com
Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>